language: ruby
cache:
  - bundler
before_install:
  - gem install bundler -v 2.4.6
rvm:
  - 2.7.6
before_script:
  - bundle install --jobs=3 --retry=3
script:
  - bundle exec rspec
  - bundle exec rubocop
